import os
import uuid
import subprocess
import tempfile
import shutil


VIDEO_OUTPUT_DIR = "/videos/pysim"


async def run_simulation_and_compile(script: str, duration_seconds: float) -> str:
    """
    Execute a simulation script and compile the output frames to video.
    
    Args:
        script: Python code for the simulation
        duration_seconds: Expected duration
        
    Returns:
        Path to the compiled video file
    """
    os.makedirs(VIDEO_OUTPUT_DIR, exist_ok=True)
    
    # Create a temporary directory for the simulation
    with tempfile.TemporaryDirectory() as temp_dir:
        script_path = os.path.join(temp_dir, "simulation.py")
        frames_dir = os.path.join(temp_dir, "frames")
        os.makedirs(frames_dir, exist_ok=True)
        
        # Write the script to a file
        with open(script_path, "w") as f:
            f.write(script)
        
        # Run the simulation
        result = subprocess.run(
            ["python", script_path, frames_dir],
            capture_output=True,
            text=True,
            cwd=temp_dir,
            timeout=300  # 5 minute timeout
        )
        
        if result.returncode != 0:
            raise RuntimeError(f"Simulation failed: {result.stderr}")
        
        # Check if frames were generated
        frames = sorted([f for f in os.listdir(frames_dir) if f.endswith('.png')])
        if not frames:
            raise RuntimeError("No frames generated by simulation")
        
        # Compile frames to video using FFmpeg
        output_filename = f"pysim_{uuid.uuid4().hex}.mp4"
        output_path = os.path.join(VIDEO_OUTPUT_DIR, output_filename)
        
        ffmpeg_result = subprocess.run(
            [
                "ffmpeg", "-y",
                "-framerate", "30",
                "-i", os.path.join(frames_dir, "frame_%05d.png"),
                "-vf", "scale=trunc(iw/2)*2:trunc(ih/2)*2",  # Ensure even dimensions for libx264
                "-c:v", "libx264",
                "-pix_fmt", "yuv420p",
                "-crf", "23",
                output_path
            ],
            capture_output=True,
            text=True
        )
        
        if ffmpeg_result.returncode != 0:
            raise RuntimeError(f"FFmpeg compilation failed: {ffmpeg_result.stderr}")
        
        return output_path
