#!/usr/bin/env python3
"""Populate SQS with 200 unique STEM video topics."""

import boto3
import json
import uuid
import time

QUEUE_URL = "https://sqs.us-east-1.amazonaws.com/482625028438/iris-flow-topic-queue"
sqs = boto3.client("sqs", region_name="us-east-1")

TOPICS = [
    # ── PARADOXES (30) ──────────────────────────────────────────────────────────
    {"prompt": "The Unexpected Hanging Paradox — a judge sentences a prisoner to be hanged on a weekday the following week, but the day must be a surprise. The prisoner reasons he can't be hanged on Friday (he'd know Thursday night), then eliminates Thursday, Wednesday... proving he can't be hanged at all. Then he's hanged on Wednesday — totally surprised. Animate the logical chain of elimination with a calendar visual, then show where the reasoning breaks down.", "category": "paradoxes"},
    {"prompt": "The Ship of Theseus — if you replace every plank of a ship one by one, is it still the same ship? Now the twist: what if someone rebuilds a second ship from all the old planks? Which one is the 'real' ship? Animate planks being swapped with glowing new ones while a shadow ship assembles from discards.", "category": "paradoxes"},
    {"prompt": "Newcomb's Paradox — a superintelligent predictor places money in two boxes. Box A always has $1,000. Box B has $1,000,000 if the predictor thinks you'll take only Box B, or $0 if it predicts you'll take both. Dominant strategy says take both, but expected value says take only B. Animate the decision tree and show why rational people disagree.", "category": "paradoxes"},
    {"prompt": "The Liar's Paradox and Gödel Numbering — 'This statement is false.' Show how this ancient paradox inspired Gödel to encode mathematical statements as numbers, creating self-referential statements that broke mathematics. Animate the encoding process and the moment of logical collapse.", "category": "paradoxes"},
    {"prompt": "The Raven Paradox (Hempel's Paradox) — observing a black raven confirms 'all ravens are black.' But logically, observing a green apple (a non-black non-raven) should ALSO confirm it. Does seeing your red car prove something about ravens? Animate the logical equivalence with Bayesian updating.", "category": "paradoxes"},
    {"prompt": "The Grandfather Paradox and Novikov's Self-Consistency Principle — if you travel back in time and prevent your grandparents from meeting, you'd never be born to travel back. Animate the causal loop, then show Novikov's resolution: the universe conspires so paradoxes can't occur.", "category": "paradoxes"},
    {"prompt": "The Sorites Paradox (Paradox of the Heap) — one grain of sand is not a heap. Adding one grain to a non-heap can't make it a heap. Therefore, no amount of sand is ever a heap. Animate grains accumulating while a 'heap-o-meter' refuses to trigger, exploring vagueness in logic.", "category": "paradoxes"},
    {"prompt": "The Crocodile Dilemma — a crocodile steals a child and promises to return it if the parent correctly predicts what the crocodile will do. The parent says 'You will not return my child.' If the crocodile returns the child, the prediction was wrong. If it doesn't, the prediction was right and it must return the child. Animate the logical deadlock.", "category": "paradoxes"},
    {"prompt": "Braess's Paradox — adding a new road to a traffic network can make EVERYONE's commute worse. Animate a simple 4-node network where a new shortcut road causes Nash equilibrium congestion that increases total travel time. Show the game theory behind it.", "category": "paradoxes"},
    {"prompt": "The Information Paradox of Black Holes — Hawking showed black holes evaporate via radiation, but quantum mechanics demands information is never destroyed. Where does the information go? Animate the conflict between general relativity and quantum mechanics at the event horizon.", "category": "paradoxes"},
    {"prompt": "Ross-Littlewood Paradox (The Infinite Vase) — at each step, add 10 balls to a vase and remove 1. After infinitely many steps, how many balls remain? The answer depends on WHICH ball you remove — it could be 0 or infinity. Animate the vase filling and emptying with numbered balls.", "category": "paradoxes"},
    {"prompt": "The Coastline Paradox — the length of a coastline depends on how you measure it. With a shorter ruler, the coast gets longer... approaching infinity. Animate measuring Britain's coastline at different scales, introducing Mandelbrot's fractal dimension.", "category": "paradoxes"},
    {"prompt": "Galileo's Paradox of Infinity — there are as many perfect squares (1, 4, 9, 16...) as natural numbers (1, 2, 3, 4...) even though squares are a tiny subset. Animate the one-to-one correspondence and show how infinity breaks our intuition about 'more' and 'less.'", "category": "paradoxes"},
    {"prompt": "The Fermi Paradox Revisited Through the Great Filter — the universe is 13.8 billion years old with 200 billion trillion stars, yet we see no aliens. Animate the Drake Equation, then walk through the Great Filter hypothesis: is the filter behind us (life is rare) or ahead of us (civilizations destroy themselves)?", "category": "paradoxes"},
    {"prompt": "Parrondo's Paradox — two losing gambling strategies that, when alternated, become a WINNING strategy. Animate the ratchet mechanism behind it: Strategy A is a simple losing coin flip, Strategy B has state-dependent odds. Alternating them exploits a Brownian ratchet effect.", "category": "paradoxes"},

    # ── COUNTERINTUITIVE PHENOMENA (30) ──────────────────────────────────────────
    {"prompt": "The Banach-Tarski Paradox in Practice — axiom of choice lets you split a sphere into 5 pieces and reassemble them into TWO identical spheres. This isn't physical duplication — it's a consequence of infinite non-measurable sets. Animate the decomposition with color-coded rotations on the surface of a sphere.", "category": "counterintuitive_phenomena"},
    {"prompt": "Quantum Tunneling — a particle with less energy than a barrier can appear on the other side. This isn't science fiction — it's how the Sun fuses hydrogen and how flash memory works. Animate a wave function hitting a potential barrier and showing the exponentially decaying probability on the far side.", "category": "counterintuitive_phenomena"},
    {"prompt": "The Dunning-Kruger Effect Mathematically — plot competence vs. confidence and show the characteristic curve: beginners are overconfident, intermediates lose confidence, experts regain it. Animate real experimental data from Kruger and Dunning's 1999 study.", "category": "counterintuitive_phenomena"},
    {"prompt": "Why Do Mirrors Flip Left-Right But Not Up-Down? — this common question has a surprising answer: mirrors don't flip left-right at all. They flip FRONT-TO-BACK. Animate a 3D coordinate transform showing what really happens when light reflects.", "category": "counterintuitive_phenomena"},
    {"prompt": "The Inspection Paradox — why the bus always seems late, your friends have more friends than you, and classes feel crowded. When you sample by 'being there,' you oversample long intervals. Animate the sampling bias with a timeline of bus arrivals.", "category": "counterintuitive_phenomena"},
    {"prompt": "The Friendship Paradox — on average, your friends have more friends than you do. This isn't depression — it's a mathematical theorem about networks. Animate a social graph showing how high-degree nodes appear in more friend lists, biasing the average.", "category": "counterintuitive_phenomena"},
    {"prompt": "Why Bees Make Hexagons — the honeycomb conjecture: hexagons are the most efficient way to tile a plane with equal-area cells using minimum perimeter. Proved by Thomas Hales in 1999 after 2000 years. Animate competing tessellations (triangles, squares, hexagons) and measure their perimeters.", "category": "counterintuitive_phenomena"},
    {"prompt": "The Surprisingly Short Chain of Acquaintances — six degrees of separation. Milgram's 1967 experiment showed any two Americans are connected through ~6 people. Animate the small-world network model: mostly local connections plus a few long-range 'shortcuts' dramatically shrink path lengths.", "category": "counterintuitive_phenomena"},
    {"prompt": "Why Hot Water Pipes Freeze First (Not the Mpemba Effect) — in buildings, hot water pipes burst before cold ones in a freeze. It's not because hot water freezes faster — it's because hot pipes have less dissolved gas, different convection patterns, and are often less insulated. Debunk the myth while explaining the real engineering.", "category": "counterintuitive_phenomena"},
    {"prompt": "The Monty Hall Problem Generalized — extend it to 100 doors. You pick one, the host opens 98 losing doors. Now switching gives you 99% odds. Animate the probability redistribution as doors open one by one, making the counterintuitive solution viscerally obvious.", "category": "counterintuitive_phenomena"},
    {"prompt": "Regression to the Mean — why the Sports Illustrated cover jinx exists, why punishing bad performance seems to work, and why miracle cures appear effective. Extreme results naturally move toward the average on remeasurement. Animate scatter plots showing the statistical illusion.", "category": "counterintuitive_phenomena"},
    {"prompt": "The Potato Paradox — a farmer has 100 lbs of potatoes that are 99% water. After drying to 98% water, how much do they weigh? The answer is 50 lbs — they lost HALF their weight by losing just 1% water content. Animate the mass balance equation with a visual scale.", "category": "counterintuitive_phenomena"},
    {"prompt": "Why the Night Sky is Dark (Olbers' Paradox) — in an infinite, eternal universe with stars everywhere, every line of sight should end at a star, making the sky blazingly bright. It's dark because the universe has a finite age and is expanding. Animate light cones and the cosmic horizon.", "category": "counterintuitive_phenomena"},
    {"prompt": "Survivorship Bias — Abraham Wald and the WWII bomber problem. The military wanted to armor the places where returning planes had bullet holes. Wald said armor the places WITHOUT holes — those planes never came back. Animate the bullet hole distribution on returning vs. lost aircraft.", "category": "counterintuitive_phenomena"},
    {"prompt": "The Pareto Principle Across Domains — 80% of effects come from 20% of causes. Show it in wealth distribution, software bugs, city populations, earthquake magnitudes, and word frequency. Animate log-log plots revealing the universal power law underneath.", "category": "counterintuitive_phenomena"},
    {"prompt": "Why Spinning Tops Don't Fall Over — gyroscopic precession. A spinning top resists gravity not by opposing it, but by converting the torque into a circular motion perpendicular to both the spin and gravity. Animate the angular momentum vectors and show precession emerging from the cross product.", "category": "counterintuitive_phenomena"},
    {"prompt": "The Penrose Triangle and Impossible Objects — objects that look valid from any single viewpoint but can't exist in 3D. Animate a Penrose triangle rotating to reveal the gap, then show how M.C. Escher exploited these for Waterfall and Ascending/Descending.", "category": "counterintuitive_phenomena"},
    {"prompt": "The Lever Rule and Why You Can't Beat a Seesaw — a child and an adult can balance on a seesaw, but the work done by gravity is the same on both sides. Animate the free body diagram and show Archimedes' 'give me a lever long enough and I shall move the world' — calculating the actual lever length needed.", "category": "counterintuitive_phenomena"},
    {"prompt": "The Wisdom of Crowds — Francis Galton's 1907 ox-weighing contest. 787 people guessed an ox's weight; the median guess was within 0.8% of the actual weight. Animate the distribution of guesses converging to the true value, then show when crowds FAIL (correlated errors, information cascades).", "category": "counterintuitive_phenomena"},
    {"prompt": "Graham's Number — a number so large that the observable universe can't contain its digits. Even the number of digits has more digits than atoms in the universe. Animate Knuth's up-arrow notation building from exponentiation to tetration to pentation, then show how Graham's Number dwarfs them all.", "category": "counterintuitive_phenomena"},

    # ── ELEGANT THEOREMS (30) ────────────────────────────────────────────────────
    {"prompt": "The Bridges of Königsberg — Euler's 1736 solution to whether you can walk across all 7 bridges without repeating one. He abstracted the map into a graph, inventing graph theory. Animate the city map morphing into nodes and edges, then show the degree-parity proof.", "category": "elegant_theorems"},
    {"prompt": "Bayes' Theorem — the math of updating beliefs. Start with a medical test: 99% accurate, disease affects 1 in 10,000. You test positive — what's the actual probability you're sick? Only 1%. Animate the tree diagram and show why base rates dominate.", "category": "elegant_theorems"},
    {"prompt": "The Central Limit Theorem — why everything is normally distributed. Drop balls through a Galton board: each ball takes random left/right bounces, but the pile at the bottom forms a perfect bell curve. Animate thousands of balls, then prove it works for ANY underlying distribution.", "category": "elegant_theorems"},
    {"prompt": "Fermat's Last Theorem — x^n + y^n = z^n has no integer solutions for n > 2. Stated in 1637, proved in 1995 by Andrew Wiles after 358 years. Animate the journey: Fermat's margin note, failed attempts, the connection to elliptic curves, Wiles' 7-year secret work, the gap, and the fix.", "category": "elegant_theorems"},
    {"prompt": "The Pythagorean Theorem — 400+ proofs exist. Animate the three most elegant: (1) Euclid's original with squares on each side, (2) the Chinese proof by rearrangement, (3) Einstein's childhood proof using similar triangles. Show how each reveals something different.", "category": "elegant_theorems"},
    {"prompt": "The Brouwer Fixed-Point Theorem — stir a cup of coffee. At least one point ends up exactly where it started. Crumple a map of your city while standing in it — one point on the map lies exactly above its real location. Animate the continuous deformation and the fixed point.", "category": "elegant_theorems"},
    {"prompt": "Shannon's Source Coding Theorem — there is a fundamental limit to how much you can compress data without losing information: the entropy. Animate a message being compressed, show the entropy calculation, and demonstrate why you can approach but never beat the Shannon limit.", "category": "elegant_theorems"},
    {"prompt": "The Hairy Ball Theorem — you can't comb a hairy sphere flat without creating a cowlick (a point where the hair converges or diverges). This is why there's always a cyclone somewhere on Earth. Animate vector fields on a sphere showing the unavoidable singularity.", "category": "elegant_theorems"},
    {"prompt": "The Ham Sandwich Theorem — given a ham sandwich (two pieces of bread and a slice of ham), there exists a single straight cut that bisects all three pieces simultaneously. This works in any dimension. Animate 2D and 3D versions with the Borsuk-Ulam theorem connection.", "category": "elegant_theorems"},
    {"prompt": "Arrow's Impossibility Theorem — no ranked voting system can satisfy three reasonable fairness criteria simultaneously: non-dictatorship, Pareto efficiency, and independence of irrelevant alternatives. Animate elections under different voting systems, showing each one violating a criterion.", "category": "elegant_theorems"},
    {"prompt": "Ramsey Theory — complete disorder is impossible. In any party of 6 people, there must exist a group of 3 who all know each other OR 3 who are all strangers. Animate the graph coloring: color edges red (friends) or blue (strangers) in K6, and show the monochromatic triangle is unavoidable.", "category": "elegant_theorems"},
    {"prompt": "The Jordan Curve Theorem — any simple closed curve in the plane divides it into exactly two regions: inside and outside. Sounds obvious but took 40 years to prove. Animate increasingly wild curves and show the ray-casting algorithm to determine inside vs. outside.", "category": "elegant_theorems"},
    {"prompt": "Lagrange's Four-Square Theorem — every positive integer can be written as the sum of at most four perfect squares. Animate decompositions: 7 = 4+1+1+1, 23 = 9+9+4+1. Show the proof idea using Euler's four-square identity.", "category": "elegant_theorems"},
    {"prompt": "The Minimax Theorem (von Neumann) — in any two-player zero-sum game, there exists an optimal mixed strategy for both players. Animate a payoff matrix, show the saddle point, and demonstrate that knowing your opponent's strategy can't help if both play optimally.", "category": "elegant_theorems"},
    {"prompt": "The Inscribed Angle Theorem — any angle inscribed in a semicircle is a right angle (Thales' theorem). Extend to: inscribed angles subtending the same arc are equal. Animate points moving along a circle while the angle stays constant — a result that feels magical.", "category": "elegant_theorems"},
    {"prompt": "Rice's Theorem — for any non-trivial property of programs, it's undecidable whether an arbitrary program has that property. You can't write a program to detect if another program sorts a list. Animate the reduction from the halting problem.", "category": "elegant_theorems"},
    {"prompt": "The Intermediate Value Theorem and its Wild Consequences — if a continuous function goes from negative to positive, it must hit zero. Simple — but it proves: at any moment, two antipodal points on Earth have the same temperature. Animate the Borsuk-Ulam application.", "category": "elegant_theorems"},
    {"prompt": "Pick's Theorem — the area of a polygon with vertices on grid points is: A = I + B/2 - 1, where I = interior points, B = boundary points. Animate various polygons on a lattice grid, counting dots and verifying the elegant formula.", "category": "elegant_theorems"},
    {"prompt": "The Gauss-Bonnet Theorem — the total curvature of a closed surface depends only on its topology. A sphere always has total curvature 4π regardless of how you deform it (as long as you don't tear or puncture it). Animate Gaussian curvature on deforming surfaces.", "category": "elegant_theorems"},
    {"prompt": "Cayley's Formula — the number of labeled trees on n vertices is exactly n^(n-2). For 4 vertices, there are 16 labeled trees. Animate all 16, then show Prüfer sequences — the bijective proof that makes the formula obvious.", "category": "elegant_theorems"},

    # ── REAL-WORLD APPLICATIONS (35) ─────────────────────────────────────────────
    {"prompt": "How GPS Uses Relativity — your phone's GPS needs both special AND general relativity corrections. Satellites move fast (time slows by 7μs/day) and are in weaker gravity (time speeds up by 45μs/day). Without corrections, GPS would drift 10 km/day. Animate the spacetime geometry.", "category": "real_world_applications"},
    {"prompt": "How Shazam Identifies Songs — audio fingerprinting using spectrogram peak detection. Convert audio to a spectrogram, find the loudest frequency peaks, hash pairs of peaks with their time difference, and match against a database. Animate the full pipeline from microphone to match.", "category": "real_world_applications"},
    {"prompt": "The RSA Algorithm — public key cryptography that secures the internet. Multiply two large primes (easy), factor the product (nearly impossible). Animate key generation, encryption, and decryption with small numbers, then show why 2048-bit keys are safe.", "category": "real_world_applications"},
    {"prompt": "How MRI Machines See Inside You — nuclear magnetic resonance. Hydrogen atoms in your body align with a magnetic field. A radio pulse knocks them out of alignment. As they relax back, they emit signals that vary by tissue type. Animate the spin physics and image reconstruction.", "category": "real_world_applications"},
    {"prompt": "JPEG Compression — your photos are stored using the Discrete Cosine Transform. Break an image into 8×8 blocks, transform to frequency space, quantize (throw away high frequencies your eyes can't see), and compress. Animate each stage showing the image degrading gracefully.", "category": "real_world_applications"},
    {"prompt": "How Bridges Handle Wind — the Tacoma Narrows disaster was NOT resonance (a common misconception). It was aeroelastic flutter: the bridge's motion changed the airflow, which changed the forces, creating a positive feedback loop. Animate the vortex shedding and torsional flutter.", "category": "real_world_applications"},
    {"prompt": "The Math Behind Spotify's Recommendations — collaborative filtering uses matrix factorization. Build a giant user-song matrix, decompose it into latent features, and predict missing entries. Animate the SVD decomposition and show how 'taste vectors' emerge.", "category": "real_world_applications"},
    {"prompt": "How CT Scans Reconstruct 3D Images from X-Rays — the Radon transform. Take X-ray projections from many angles, apply the inverse Radon transform (filtered back-projection) to reconstruct cross-sectional slices. Animate sinograms building into sharp images.", "category": "real_world_applications"},
    {"prompt": "Why Airplane Wings Generate Lift — it's NOT because air travels faster over the curved top (the equal transit time fallacy). It's Newton's third law: wings deflect air downward, so air pushes the wing up. Animate the real pressure distribution and circulation theory.", "category": "real_world_applications"},
    {"prompt": "How Bitcoin Mining Actually Works — SHA-256 hashing, proof of work, and the nonce search. Miners must find a number that, when hashed with the block data, produces a hash starting with N zeros. Animate the hash function, the brute-force search, and difficulty adjustment.", "category": "real_world_applications"},
    {"prompt": "The Kalman Filter — how your phone smoothly tracks your position despite noisy GPS. Predict where you'll be, measure where the GPS says you are, and blend them optimally based on uncertainty. Animate the Gaussian distributions narrowing as prediction meets measurement.", "category": "real_world_applications"},
    {"prompt": "How Vaccines Train Your Immune System — animate the adaptive immune response: antigen presentation, T-cell activation, B-cell antibody production, and memory cell formation. Show how mRNA vaccines deliver instructions without the actual virus.", "category": "real_world_applications"},
    {"prompt": "The Fast Fourier Transform — the algorithm that changed the world. O(N log N) instead of O(N²). Cooley and Tukey's 1965 paper enabled digital signal processing, medical imaging, and modern telecommunications. Animate the butterfly diagram and the divide-and-conquer recursion.", "category": "real_world_applications"},
    {"prompt": "How Noise-Canceling Headphones Work — destructive interference. Record ambient noise, invert its phase, and play it back. The anti-noise cancels the noise. Animate sine waves: original + inverted = silence. Then show the real challenges: latency, frequency response, and feedback.", "category": "real_world_applications"},
    {"prompt": "The Bellman Equation and How Google Maps Finds the Shortest Path — dynamic programming breaks the shortest path into subproblems. Dijkstra's algorithm explores outward like a ripple. A* adds a heuristic to focus the search. Animate all three on a real road network.", "category": "real_world_applications"},
    {"prompt": "How Fiber Optics Carry the Internet — total internal reflection. Light enters a glass fiber at a steep angle and bounces along the core without escaping. Wavelength-division multiplexing sends multiple colors simultaneously. Animate the ray optics and the Snell's law math.", "category": "real_world_applications"},
    {"prompt": "Principal Component Analysis (PCA) — reduce high-dimensional data to its essence. Find the directions of maximum variance, project the data, and keep only the top components. Animate a 3D point cloud collapsing to 2D while preserving structure.", "category": "real_world_applications"},
    {"prompt": "How CRISPR-Cas9 Edits DNA — the Cas9 protein uses a guide RNA to find a specific DNA sequence, then cuts both strands. The cell's repair machinery either disables the gene or inserts new DNA. Animate the molecular machinery: guide RNA binding, PAM recognition, and the double-strand break.", "category": "real_world_applications"},
    {"prompt": "The Navier-Stokes Equations — the unsolved millennium problem governing all fluid flow. Animate turbulent flow in a pipe: laminar at low Reynolds numbers, then the chaotic transition. Show why proving smooth solutions exist is worth $1 million.", "category": "real_world_applications"},
    {"prompt": "How QR Codes Store Data — Reed-Solomon error correction, masking patterns, and format information. A QR code can lose up to 30% of its area and still be read. Animate encoding a URL: data → polynomial → error correction → module placement → masking.", "category": "real_world_applications"},
    {"prompt": "The Monte Carlo Method — solve hard problems by random sampling. Estimate π by throwing darts at a square containing a circle. Extend to option pricing, radiation therapy planning, and nuclear physics. Animate convergence as sample size grows.", "category": "real_world_applications"},
    {"prompt": "How Electric Motors Work — Lorentz force. Current-carrying wire in a magnetic field experiences a force. Arrange coils and magnets to create continuous rotation. Animate the force vectors, commutation, and back-EMF that limits speed.", "category": "real_world_applications"},
    {"prompt": "Diffie-Hellman Key Exchange — two people can create a shared secret over an insecure channel. Mix paint analogy: you both start with a common color, add your secret color, exchange mixtures, then add your secret again. Both arrive at the same final color. Animate with actual modular arithmetic.", "category": "real_world_applications"},
    {"prompt": "How Autofocus Works in Cameras — contrast detection vs. phase detection. Contrast AF maximizes edge sharpness by trying different focus positions. Phase AF uses split-beam sensors to determine direction and distance to focus instantly. Animate both optical paths.", "category": "real_world_applications"},
    {"prompt": "The Levenshtein Distance and Spell Checkers — the minimum number of single-character edits (insertions, deletions, substitutions) to transform one word into another. Animate the dynamic programming table being filled for 'kitten' → 'sitting', then show how autocorrect ranks suggestions.", "category": "real_world_applications"},

    # ── MATHEMATICAL PATTERNS (35) ───────────────────────────────────────────────
    {"prompt": "Voronoi Diagrams in Nature — every point in space belongs to the nearest seed point's territory. Show Voronoi patterns in giraffe skin, dragonfly wings, mud cracks, foam bubbles, and cell growth. Animate seeds dropping and boundaries forming via Fortune's algorithm.", "category": "mathematical_patterns"},
    {"prompt": "The Mandelbrot Set Zoom — iterate z → z² + c and color by escape speed. Zoom into the boundary between the main cardioid and the first bulb, revealing infinite copies of the whole set at every scale. Animate a smooth zoom with color cycling.", "category": "mathematical_patterns"},
    {"prompt": "Euler's Polyhedron Formula — V - E + F = 2 for any convex polyhedron. Verify on a cube (8-12+6=2), tetrahedron (4-6+4=2), dodecahedron (20-30+12=2). Then show it fails for a torus (V-E+F=0) because topology matters. Animate faces being removed and recounted.", "category": "mathematical_patterns"},
    {"prompt": "The Koch Snowflake — start with an equilateral triangle. Replace each edge's middle third with a smaller triangle. Repeat infinitely: the perimeter goes to infinity but the area converges. Animate iterations 0-6 and plot perimeter vs. area.", "category": "mathematical_patterns"},
    {"prompt": "Cellular Automata and Rule 110 — a single row of cells evolving by a simple rule produces universal computation. Animate Rule 30 (chaos from order), Rule 110 (complexity), and Rule 184 (traffic flow). Show how Stephen Wolfram's classification categorizes all 256 elementary rules.", "category": "mathematical_patterns"},
    {"prompt": "The Golden Ratio in Phyllotaxis — why sunflower seeds spiral in Fibonacci numbers (34 clockwise, 55 counterclockwise). Each new seed grows at 137.5° (the golden angle) from the last, packing most efficiently. Animate seeds appearing one by one, with spiral counts updating.", "category": "mathematical_patterns"},
    {"prompt": "Penrose Tilings — two shapes (kites and darts) tile the plane with five-fold symmetry but NEVER repeat. The pattern is aperiodic — no translation maps it onto itself. Animate the matching rules and show how the ratio of kites to darts approaches the golden ratio.", "category": "mathematical_patterns"},
    {"prompt": "The Catalan Numbers — 1, 1, 2, 5, 14, 42, 132... They count balanced parentheses, binary trees, polygon triangulations, mountain ranges, and non-crossing partitions. Animate all five interpretations for C₄ = 14, showing the bijections between them.", "category": "mathematical_patterns"},
    {"prompt": "Lissajous Curves — plot x = sin(at + δ), y = sin(bt). When a/b is rational, you get closed curves. When irrational, the curve fills a rectangle. Animate different frequency ratios: 1:1 (ellipse), 1:2 (figure-8), 3:2 (pretzel), and the transition as ratios approach irrationals.", "category": "mathematical_patterns"},
    {"prompt": "The Ulam Spiral — write integers in a spiral and highlight the primes. Diagonal lines appear where none should exist, hinting at deep structure in prime distribution. Animate the spiral growing to 10,000 with primes lighting up.", "category": "mathematical_patterns"},
    {"prompt": "Dragon Curves — fold a strip of paper in half repeatedly, always in the same direction. Unfold to 90° angles. The resulting curve is a fractal that tiles the plane. Animate the unfolding process and show how four dragon curves fit together perfectly.", "category": "mathematical_patterns"},
    {"prompt": "Taxicab Numbers — 1729 is the smallest number expressible as the sum of two cubes in two different ways (1³ + 12³ = 9³ + 10³). Hardy's boring taxi number turned out to be beautiful. Animate the search through cube sums and show the Ramanujan connection.", "category": "mathematical_patterns"},
    {"prompt": "The Stern-Brocot Tree — every positive rational number appears exactly once in this infinite binary tree. Start with 0/1 and 1/0, and mediant (a+c)/(b+d) between neighbors generates all fractions in lowest terms. Animate the tree growing and show its connection to continued fractions.", "category": "mathematical_patterns"},
    {"prompt": "Reaction-Diffusion Patterns (Turing Patterns) — Alan Turing showed that two chemicals diffusing at different rates can create stable patterns: spots, stripes, and spirals. This explains leopard spots and zebrafish stripes. Animate the Gray-Scott model producing these patterns from random noise.", "category": "mathematical_patterns"},
    {"prompt": "Apollonian Gaskets — start with three mutually tangent circles, then fill each gap with the largest circle that fits. Repeat infinitely. The curvatures satisfy Descartes' Circle Theorem. Animate the gasket forming and show the beautiful integer curvature sequences.", "category": "mathematical_patterns"},
    {"prompt": "Conway's Look-and-Say Sequence — 1, 11, 21, 1211, 111221... Each term describes the previous. The length grows by a factor of λ ≈ 1.303577... (Conway's constant) per step. Animate the 'reading' process and show the surprising connection to cosmological theory.", "category": "mathematical_patterns"},
    {"prompt": "The Farey Sequence — list all fractions between 0 and 1 with denominator ≤ n. Adjacent fractions a/b and c/d satisfy |ad - bc| = 1. Animate Farey sequences for n = 1 to 10 on a number line, showing the mediant property and the connection to the Riemann hypothesis.", "category": "mathematical_patterns"},
    {"prompt": "Minimal Surfaces and Soap Films — soap films minimize surface area, solving complex optimization problems. A soap film between two rings forms a catenoid. Between wire frames, it finds surfaces mathematicians struggled to compute. Animate the mean curvature flow.", "category": "mathematical_patterns"},
    {"prompt": "The Hilbert Curve — a space-filling curve that visits every point in a square. At each iteration, the 1D line better approximates the 2D square. Animate iterations 1-7 and show the real application: preserving locality in database indexing and image processing.", "category": "mathematical_patterns"},
    {"prompt": "Platonic Solids — only 5 exist (tetrahedron, cube, octahedron, dodecahedron, icosahedron). Prove it using Euler's formula and the constraint that each vertex must have at least 3 faces with angles summing to less than 360°. Animate each solid rotating with dual pairs highlighted.", "category": "mathematical_patterns"},

    # ── PHYSICS PHENOMENA (40) ───────────────────────────────────────────────────
    {"prompt": "The Meissner Effect — cool a superconductor below its critical temperature and it expels ALL magnetic fields, causing a magnet to levitate. This isn't just diamagnetism — it's a quantum effect involving Cooper pairs. Animate the magnetic field lines being expelled and the levitation force diagram.", "category": "physics_phenomena"},
    {"prompt": "Cherenkov Radiation — the blue glow in nuclear reactors. When a charged particle moves faster than light IN WATER (not vacuum), it creates an electromagnetic shockwave — the optical equivalent of a sonic boom. Animate the wavefront cone and the Mach-like angle.", "category": "physics_phenomena"},
    {"prompt": "The Photoelectric Effect — shine UV light on metal and electrons fly off. But increase the intensity of red light and NOTHING happens. Einstein explained this with photons: energy depends on frequency, not intensity. This won him the Nobel Prize, not relativity. Animate the threshold frequency.", "category": "physics_phenomena"},
    {"prompt": "Sonoluminescence — collapse a tiny bubble with sound waves and it briefly reaches temperatures hotter than the sun's surface, emitting a flash of light. A single bubble in water, pulsed by ultrasound, produces picosecond flashes. Animate the bubble dynamics and the mystery of the mechanism.", "category": "physics_phenomena"},
    {"prompt": "The Coriolis Effect — why hurricanes spin counterclockwise in the Northern Hemisphere. It's not a real force — it's the consequence of being on a rotating reference frame. Animate a ball thrown on a rotating platform, then scale up to weather systems.", "category": "physics_phenomena"},
    {"prompt": "Bose-Einstein Condensation — cool atoms to near absolute zero and they all collapse into the same quantum state, behaving as one giant 'super-atom.' Animate the velocity distribution narrowing as temperature drops, and show the matter wave coherence.", "category": "physics_phenomena"},
    {"prompt": "The Doppler Effect for Light — redshift and blueshift. An approaching star's light compresses (blueshift), a receding star's light stretches (redshift). Hubble used this to discover the universe is expanding. Animate wavefronts compressing and stretching with the relativistic formula.", "category": "physics_phenomena"},
    {"prompt": "Lenz's Law and Electromagnetic Braking — drop a magnet through a copper tube and it falls in slow motion. Eddy currents create opposing magnetic fields. No mechanical contact, yet the magnet practically floats down. Animate the induced currents and opposing force vectors.", "category": "physics_phenomena"},
    {"prompt": "The Oberth Effect — firing a rocket at maximum speed (near periapsis) gives more energy than firing at minimum speed. The same fuel produces more kinetic energy when the rocket is already moving fast. This is why spacecraft do 'gravity assist' burns. Animate the energy calculation.", "category": "physics_phenomena"},
    {"prompt": "Rayleigh Scattering — why the sky is blue and sunsets are red. Short wavelengths scatter more (∝ 1/λ⁴). At noon, blue scatters toward you. At sunset, light travels through more atmosphere, scattering away all blue, leaving red. Animate photons scattering through the atmosphere.", "category": "physics_phenomena"},
    {"prompt": "Quantum Entanglement — measure one particle and you instantly know the other's state, no matter the distance. Einstein called it 'spooky action at a distance.' Bell's theorem proved it's real — no hidden variables. Animate the Bell test experiment and the violation of Bell's inequality.", "category": "physics_phenomena"},
    {"prompt": "The Piezoelectric Effect — squeeze certain crystals (quartz) and they produce voltage. Apply voltage and they deform. This is how quartz watches keep time: a tiny crystal vibrates 32,768 times per second. Animate the lattice deformation and the oscillator circuit.", "category": "physics_phenomena"},
    {"prompt": "Triboluminescence — snap a Wint-O-Green Life Saver in the dark and it sparks blue. Crushing sugar crystals generates charge separation and UV light, which the wintergreen oil absorbs and re-emits as visible blue. Animate the crystal fracture, charge separation, and fluorescence.", "category": "physics_phenomena"},
    {"prompt": "The Bernoulli Principle Correctly Explained — it's NOT about air speed over a curved wing. Bernoulli's equation is about energy conservation in a streamline: pressure + kinetic + potential energy = constant. Animate a venturi tube, a carburetor, and an atomizer.", "category": "physics_phenomena"},
    {"prompt": "Neutron Stars and Nuclear Pasta — at the core of a neutron star, nuclear matter arranges into lasagna-like sheets, spaghetti-like tubes, and gnocchi-like bubbles. These are the strongest materials in the universe. Animate the density gradient from crust to core.", "category": "physics_phenomena"},
    {"prompt": "The Carnot Cycle — the maximum possible efficiency of any heat engine. Animate the four steps: isothermal expansion, adiabatic expansion, isothermal compression, adiabatic compression. Show why no real engine reaches Carnot efficiency and what entropy has to do with it.", "category": "physics_phenomena"},
    {"prompt": "Acoustic Levitation — standing sound waves create nodes of zero pressure where small objects can float. No magic, just constructive and destructive interference. Animate the pressure nodes, anti-nodes, and a small droplet trapped at a node.", "category": "physics_phenomena"},
    {"prompt": "Frame Dragging (Lense-Thirring Effect) — a spinning massive object drags spacetime around with it like a whirlpool. Gravity Probe B confirmed this by measuring tiny gyroscope precessions near Earth. Animate the twisted spacetime geometry around a spinning black hole.", "category": "physics_phenomena"},
    {"prompt": "Resonance and the Millennium Bridge — London's Millennium Bridge opened in 2000 and immediately started swaying. Pedestrians unconsciously synchronized their steps, creating a positive feedback loop. Animate the coupled oscillator dynamics and the damper solution.", "category": "physics_phenomena"},
    {"prompt": "The Casimir Effect in Detail — two uncharged metal plates in vacuum experience an attractive force because virtual quantum fluctuations between the plates have fewer allowed wavelengths than outside. The vacuum pushes them together. Animate the mode counting between and outside the plates.", "category": "physics_phenomena"},
    {"prompt": "Spaghettification Near a Black Hole — tidal forces near a stellar black hole stretch objects into long thin strands. Your feet, being closer to the singularity, accelerate faster than your head. Animate the tidal tensor and the stretching of an infalling astronaut.", "category": "physics_phenomena"},
    {"prompt": "The Kelvin-Helmholtz Instability — when two fluids slide past each other at different speeds, the interface develops beautiful rolling waves. Visible in Jupiter's atmosphere, ocean waves, and clouds. Animate the velocity shear creating the characteristic spiral pattern.", "category": "physics_phenomena"},
    {"prompt": "Dielectric Breakdown and Lightning — air is an insulator until ~3 million V/m, then electrons cascade in an avalanche. A stepped leader zigzags down, a return stroke blazes up at 1/3 the speed of light. Animate the charge separation in clouds and the step leader propagation.", "category": "physics_phenomena"},
    {"prompt": "Time Crystals — a phase of matter that repeats in TIME, not space. Atoms in a time crystal oscillate between states forever without energy input, breaking time-translation symmetry. Animate the discrete time crystal driven by periodic pulses, showing the period-doubled response.", "category": "physics_phenomena"},
    {"prompt": "The Hall Effect — pass current through a conductor in a magnetic field and a voltage appears perpendicular to both. This reveals the sign of charge carriers (electrons vs. holes). Animate the Lorentz force deflecting carriers and the resulting voltage buildup.", "category": "physics_phenomena"},

    # ── GENERAL / CROSS-DISCIPLINARY (remaining to reach 200) ────────────────────
    {"prompt": "The Antikythera Mechanism's Gear Ratios — this 2000-year-old Greek computer predicted eclipses using epicyclic gearing. Recent X-ray tomography revealed 37 meshing bronze gears encoding the Metonic cycle (19 years = 235 lunar months). Animate the gear train and show how it tracked the Moon's elliptical orbit.", "category": "general"},
    {"prompt": "Von Karman Vortex Streets — fluid flowing past a cylinder sheds alternating vortices, visible in cloud patterns behind islands. The Strouhal number predicts the shedding frequency. Animate the vortex formation and show real satellite images of atmospheric examples.", "category": "general"},
    {"prompt": "How Your Eyes Detect Color — three types of cone cells (S, M, L) with overlapping absorption spectra. Color is a neural construction: 'yellow' activates both M and L cones. Metamers: different spectra can look identical. Animate the cone responses and show why monitors use RGB.", "category": "general"},
    {"prompt": "The Jevons Paradox — making a resource more efficient to use leads to MORE consumption, not less. Jevons observed this with coal in 1865. It applies to fuel efficiency, LED lighting, and data storage. Animate the supply-demand curves shifting with efficiency gains.", "category": "general"},
    {"prompt": "The Traveling Salesman Problem and Christofides' Algorithm — for N cities, there are (N-1)!/2 possible routes. For 20 cities, that's 60 quadrillion. Christofides' 1976 algorithm guarantees a route within 1.5x optimal. Animate the minimum spanning tree, odd-degree matching, and Euler circuit shortcutting.", "category": "general"},
    {"prompt": "The Zipf Distribution — the most common word in English ('the') appears twice as often as the second most common ('of'), three times the third, etc. Rank × frequency ≈ constant. Animate word frequencies from a real corpus, then show Zipf's law in city populations and income.", "category": "general"},
    {"prompt": "How Transistors Actually Work — a MOSFET has source, gate, and drain. Apply voltage to the gate: the electric field creates a channel of charge carriers between source and drain, switching from insulator to conductor. Animate the band diagrams and the inversion layer forming.", "category": "general"},
    {"prompt": "The Remarkable Number e — Euler's number appears in compound interest (the limit of (1+1/n)^n), radioactive decay, the bell curve, and the shape of a hanging chain. Animate these four appearances and show they're all the same constant.", "category": "general"},
    {"prompt": "How Microwaves Heat Food — microwaves oscillate water molecules 2.45 billion times per second. The molecules try to align with the field, creating friction heat. But the wavelength (~12 cm) creates standing waves — hence cold spots. Animate the dipole rotation and standing wave pattern.", "category": "general"},
    {"prompt": "The Tragedy of the Commons — Hardin's 1968 paper modeled how individual rational behavior destroys shared resources. Animate a grazing pasture: each herder benefits from adding one more cow, but the pasture degrades for everyone. Show the Nash equilibrium vs. social optimum.", "category": "general"},
    {"prompt": "Siphons — how they really work. It's NOT atmospheric pressure pulling the water (they work in vacuum, as demonstrated in 2010). The leading theory involves molecular cohesion: water molecules chain together, and gravity on the long side pulls the whole chain. Animate the force balance.", "category": "general"},
    {"prompt": "The Secretary Problem (Optimal Stopping) — interview N candidates sequentially. After rejecting someone, you can't go back. The optimal strategy: reject the first N/e ≈ 37% of candidates, then hire the next one who's better than all you've seen. Animate the decision process and prove the 1/e success probability.", "category": "general"},
    {"prompt": "Why Is Glass Transparent? — visible photons don't have enough energy to excite electrons across glass's wide band gap (~9 eV). The photons pass through. UV photons DO have enough energy — that's why glass blocks UV. Animate the band structure and photon absorption/transmission.", "category": "general"},
    {"prompt": "The Mathematics of Gerrymandering — how drawing district boundaries changes election outcomes. Show the same population split into districts where one party wins 60% or 80% of seats depending on the map. Animate the efficiency gap metric and Markov chain Monte Carlo sampling of fair maps.", "category": "general"},
    {"prompt": "How Your Inner Ear Detects Sound — the cochlea performs a real-time Fourier transform. Sound waves enter the fluid-filled spiral, and different positions along the basilar membrane resonate at different frequencies. Hair cells convert vibrations to electrical signals. Animate the traveling wave.", "category": "general"},
    {"prompt": "Stigmergy — how termites build cathedral-like mounds without a blueprint. Each termite follows simple rules: drop pheromone-laced mud where you smell pheromone. The structure self-organizes through positive feedback. Animate agents following local rules producing global architecture.", "category": "general"},
    {"prompt": "The Butterfly Effect and Sensitivity to Initial Conditions — Edward Lorenz's 1961 weather model diverged wildly when he rounded 0.506127 to 0.506. Plot two Lorenz attractors from nearly identical starting points and watch them diverge. Animate the trajectories splitting on the strange attractor.", "category": "general"},
    {"prompt": "Why Soap Bubbles Are Spheres — a sphere has the minimum surface area for a given volume (the isoperimetric inequality). Surface tension minimizes the film's energy, naturally forming a sphere. Animate the variational calculus proof and show non-spherical bubbles relaxing to spheres.", "category": "general"},
    {"prompt": "The Doppler Effect and Exoplanet Detection — a star with an orbiting planet wobbles slightly. This wobble shifts the star's spectral lines red and blue periodically. Animate the radial velocity method: the star's spectrum oscillating, revealing an invisible planet's mass and orbit.", "category": "general"},
    {"prompt": "Amdahl's Law — adding more processors can't speed up a program beyond its serial bottleneck. If 5% of code is serial, you can never get more than 20x speedup, even with infinite processors. Animate the parallel fraction shrinking as processors increase.", "category": "general"},

    # ── ADDITIONAL TOPICS (55 more to reach 200) ─────────────────────────────────
    {"prompt": "The Monge-Kantorovich Optimal Transport Problem — what's the cheapest way to move a pile of sand into a hole? This 18th-century problem revolutionized economics, machine learning (Wasserstein GANs), and geometry. Animate sand grains flowing along optimal paths.", "category": "elegant_theorems"},
    {"prompt": "Supercritical Fluids — above certain temperature and pressure, the boundary between liquid and gas disappears. CO₂ becomes a supercritical fluid used to decaffeinate coffee. Animate the phase diagram and the critical point where meniscus vanishes.", "category": "physics_phenomena"},
    {"prompt": "The Banach Fixed-Point Theorem — any contraction mapping has exactly one fixed point, and iterating from anywhere converges to it. This is why repeatedly pressing cos on a calculator converges to 0.7391. Animate the cobweb diagram spiraling to the fixed point.", "category": "elegant_theorems"},
    {"prompt": "How Holograms Work — a hologram records interference between a reference beam and light reflected from an object. When illuminated, the film recreates the 3D wavefront. Animate the recording process, the interference fringes, and the playback reconstruction.", "category": "real_world_applications"},
    {"prompt": "The Monty Hall Problem with Bayesian Networks — model the doors, the host's choice, and your switch decision as a Bayesian network. Show how conditional probability flows through the graph to prove switching wins 2/3 of the time.", "category": "counterintuitive_phenomena"},
    {"prompt": "Quasicrystals — Dan Shechtman discovered a material with five-fold symmetry in 1982, which crystallography said was impossible. He won the Nobel Prize in 2011. Animate the diffraction pattern with its forbidden symmetry and show Penrose tiling as a 2D analog.", "category": "physics_phenomena"},
    {"prompt": "The Sleeping Barber Problem — a classic concurrency dilemma. A barber sleeps when no customers come. Customers leave if all chairs are full. Show how semaphores and mutexes solve the race conditions. Animate threads as people and locks as doors.", "category": "real_world_applications"},
    {"prompt": "Gravitational Lensing — massive objects bend light, acting as cosmic magnifying glasses. Einstein predicted it; Eddington confirmed it in 1919. Animate light paths curving around a galaxy cluster, producing Einstein rings and multiple images of distant quasars.", "category": "physics_phenomena"},
    {"prompt": "The Prisoner's Dilemma Tournament — Robert Axelrod's 1980 tournament proved that Tit-for-Tat (cooperate first, then copy opponent) beats sophisticated strategies. Animate rounds of the tournament showing how cooperation evolves even among selfish agents.", "category": "real_world_applications"},
    {"prompt": "Benford's Law Applied to Fraud Detection — financial fraudsters fabricate numbers that look random, but real financial data follows Benford's Law (30% start with digit 1). Animate the expected vs. observed distributions and show how forensic accountants catch cheaters.", "category": "real_world_applications"},
    {"prompt": "The Navier-Stokes Equations and Turbulence — Reynolds number determines whether flow is laminar or turbulent. Animate fluid in a pipe transitioning from smooth laminar flow to chaotic turbulence as velocity increases, showing the energy cascade from large to small eddies.", "category": "physics_phenomena"},
    {"prompt": "How Neural Networks Actually Learn — gradient descent on a loss landscape. Animate a ball rolling down a high-dimensional surface, getting stuck in local minima, escaping via momentum, and converging. Show backpropagation computing the gradient chain.", "category": "real_world_applications"},
    {"prompt": "The Dunbar Number — humans can maintain about 150 stable relationships. This limit comes from neocortex size. Animate a social network growing: close friends (5), good friends (15), friends (50), acquaintances (150), and the cognitive load at each level.", "category": "general"},
    {"prompt": "Why Snowflakes Are Hexagonal — water molecules form hydrogen bonds at 104.5° angles, creating a hexagonal crystal lattice. Each arm grows identically because they experience the same temperature and humidity. Animate molecular bonding creating the six-fold symmetry.", "category": "mathematical_patterns"},
    {"prompt": "Emergent Behavior in Flocking — Craig Reynolds' Boids algorithm: three rules (separation, alignment, cohesion) create realistic flocking. No leader, no global plan. Animate 200 boids following only local rules, producing mesmerizing murmuration patterns.", "category": "general"},
    {"prompt": "The Halting Problem — Alan Turing proved in 1936 that no algorithm can determine whether an arbitrary program will halt or run forever. Animate the diagonalization proof: assume a halting detector exists, then construct a program that contradicts it.", "category": "elegant_theorems"},
    {"prompt": "How Lithium-Ion Batteries Work — lithium ions shuttle between graphite anode and metal oxide cathode through an electrolyte. Charging forces ions one way; discharging lets them flow back, driving electrons through the circuit. Animate the intercalation process.", "category": "real_world_applications"},
    {"prompt": "The Strong Law of Large Numbers — flip a coin a million times: the fraction of heads converges to exactly 0.5 with probability 1. Not approximately — EXACTLY. Animate the running average stabilizing, showing the difference between the weak and strong laws.", "category": "elegant_theorems"},
    {"prompt": "Metamaterials and Negative Refraction — engineered structures with properties not found in nature. A metamaterial with negative refractive index bends light the 'wrong' way, enabling theoretical invisibility cloaks. Animate Snell's law with negative n.", "category": "physics_phenomena"},
    {"prompt": "Simpson's Rule and Numerical Integration — approximate any integral by fitting parabolas through groups of three points. Much more accurate than rectangles (Riemann) or trapezoids. Animate the parabolic approximation converging to the exact integral.", "category": "mathematical_patterns"},
    {"prompt": "The Water Hammer Effect — suddenly close a valve in a pipe and a pressure wave travels back at the speed of sound in water (~1500 m/s), creating a banging sound that can burst pipes. Animate the pressure wave bouncing back and forth in the pipe.", "category": "physics_phenomena"},
    {"prompt": "Epidemic Modeling with SIR — Susceptible, Infected, Recovered. Three differential equations model disease spread. R₀ > 1 means an epidemic. Animate the curves and show how vaccination reduces R₀ below 1, achieving herd immunity.", "category": "real_world_applications"},
    {"prompt": "The Riemann Zeta Function and its Non-Trivial Zeros — ζ(s) = Σ 1/n^s connects prime numbers to complex analysis. The Riemann Hypothesis states all non-trivial zeros have real part 1/2. Animate the critical strip, the zeta function spiraling through the complex plane, and zeros landing on the critical line.", "category": "mathematical_patterns"},
    {"prompt": "Surface Tension and Capillary Action — water climbs up narrow tubes against gravity because adhesion to glass exceeds cohesion between water molecules. The height follows Jurin's law: h = 2γcos(θ)/(ρgr). Animate molecules climbing the tube walls.", "category": "physics_phenomena"},
    {"prompt": "How Error Correction Works in Space Communication — Voyager uses Reed-Solomon and convolutional codes. A message of 223 bytes becomes 255 bytes, tolerating up to 16 byte errors. Animate the encoding polynomial, the syndrome calculation, and error location.", "category": "real_world_applications"},
    {"prompt": "The Birthday Attack in Cryptography — to find two people with the same birthday you only need 23 people (not 183). To find a hash collision in a 256-bit space, you need ~2^128 tries, not 2^256. Animate the probability calculation and its implications for hash function security.", "category": "general"},
    {"prompt": "Chaos Theory and the Logistic Map — x_{n+1} = rx_n(1-x_n). For r < 3, it converges. At r ≈ 3.57, chaos begins. Animate the bifurcation diagram forming as r increases, then zoom in to reveal self-similar copies of the whole diagram.", "category": "mathematical_patterns"},
    {"prompt": "Tensegrity Structures — sculptures and structures that appear to defy gravity using a balance of compression (rigid bars) and tension (cables). Kenneth Snelson's towers are the iconic example. Animate the force balance showing how tension members create stable equilibrium.", "category": "general"},
    {"prompt": "The Magnus Effect in Sports — a spinning ball curves through air. Topspin makes it dip, backspin makes it float, sidespin makes it curve. Animate the pressure differential created by the spinning boundary layer on a soccer ball during a free kick.", "category": "physics_phenomena"},
    {"prompt": "The Stable Marriage Problem — Gale-Shapley algorithm guarantees a stable matching where no pair would prefer to leave their partners for each other. Animate proposals and rejections over multiple rounds until the stable matching emerges.", "category": "elegant_theorems"},
    {"prompt": "How PCR (Polymerase Chain Reaction) Amplifies DNA — denature at 95°C, anneal primers at 55°C, extend at 72°C. Each cycle doubles the DNA. After 30 cycles: over 1 billion copies from a single molecule. Animate the temperature cycling and exponential amplification.", "category": "real_world_applications"},
    {"prompt": "The Brachistochrone vs. Tautochrone — the curve of fastest descent (cycloid) is ALSO the curve where travel time is independent of starting position (tautochrone). Huygens used this for pendulum clocks. Animate balls released from different heights on a cycloid arriving simultaneously.", "category": "elegant_theorems"},
    {"prompt": "Radiometric Dating and Half-Lives — Carbon-14 has a half-life of 5,730 years. After each half-life, half the C-14 atoms decay to N-14. Measure the ratio to date organic material up to ~50,000 years. Animate the exponential decay curve and the measurement process.", "category": "general"},
    {"prompt": "The Wigner Semicircle Law — the eigenvalues of large random symmetric matrices follow a semicircular distribution. This connects random matrix theory to nuclear physics, number theory, and wireless communications. Animate eigenvalues of growing matrices converging to the semicircle.", "category": "mathematical_patterns"},
    {"prompt": "Cymatics — vibrate a metal plate with sand on it and the sand collects along nodal lines (Chladni figures). Each frequency produces a unique geometric pattern. Animate the standing wave modes and the sand migrating to nodes for increasing frequencies.", "category": "physics_phenomena"},
    {"prompt": "How Solar Cells Convert Light to Electricity — photons excite electrons across the bandgap of silicon, creating electron-hole pairs. The p-n junction's electric field separates them, driving current. Animate the band diagram, photon absorption, and carrier separation.", "category": "real_world_applications"},
    {"prompt": "The Towers of Hanoi and Its 2^n - 1 Solution — move n disks from one peg to another, never placing a larger disk on a smaller one. The recursive solution requires exactly 2^n - 1 moves. With 64 disks, that's 18.4 quintillion moves. Animate the recursion tree alongside the physical moves.", "category": "mathematical_patterns"},
    {"prompt": "The Surprising Math of Paper Folding — fold paper in half 42 times and it reaches the Moon. Each fold doubles thickness: 0.1mm × 2^42 = 439,805 km. But you can't fold paper more than ~7 times because the length required grows exponentially. Animate the Britney Gallivan equation.", "category": "counterintuitive_phenomena"},
    {"prompt": "How LiDAR Maps the World — fire millions of laser pulses per second, measure return time to calculate distance. Point clouds build 3D maps used in self-driving cars, archaeology (discovering Mayan cities under jungle), and flood modeling. Animate the scanning and point cloud assembly.", "category": "real_world_applications"},
    {"prompt": "Maxwell's Equations — four equations unify electricity, magnetism, and light. A changing electric field creates a magnetic field (and vice versa), producing self-sustaining electromagnetic waves. Animate each equation's physical meaning and show the wave emerging from oscillating charges.", "category": "physics_phenomena"},
    {"prompt": "The Invariance of the Speed of Light — no matter how fast you move, light always passes you at c. If you're on a spaceship at 0.9c and turn on headlights, the light STILL moves at c relative to you. Animate the Michelson-Morley experiment and the Lorentz transformations.", "category": "physics_phenomena"},
    {"prompt": "The St. Petersburg Paradox — a coin flip game where heads on flip n pays $2^n. Expected value is infinite, yet nobody would pay $1,000 to play. Daniel Bernoulli's resolution: diminishing marginal utility. Animate the expected value diverging vs. the utility function converging.", "category": "paradoxes"},
    {"prompt": "How 3D Printers Work Layer by Layer — FDM extrudes melted plastic, SLA cures resin with UV laser, SLS sinters powder with laser. Animate the G-code toolpath for a single layer, then stack layers showing how overhangs require support structures.", "category": "real_world_applications"},
    {"prompt": "The Unexpected Power of Exponential Growth — the lily pad covers half the pond on day 29 and the whole pond on day 30. Rice on a chessboard: 2^64 - 1 grains = 18 quintillion. Animate both scenarios showing how humans consistently underestimate exponential curves.", "category": "counterintuitive_phenomena"},
    {"prompt": "The Euler Characteristic and Topology — a sphere has χ = 2, a torus has χ = 0, a double torus has χ = -2. Animate deforming shapes (stretching, bending, NOT cutting) and show that V - E + F stays constant through all deformations.", "category": "elegant_theorems"},
    {"prompt": "Stochastic Resonance — sometimes adding NOISE to a weak signal makes it MORE detectable, not less. Crayfish use this to detect predators. Animate a sub-threshold signal, add noise, and show the signal emerging via threshold crossings.", "category": "physics_phenomena"},
    {"prompt": "The Pigeonhole Principle's Surprising Consequences — if 367 people are in a room, at least two share a birthday. If you pick 5 points inside an equilateral triangle of side 1, at least two are within distance 0.5. Animate both proofs with the pigeonholes visualized.", "category": "elegant_theorems"},
    {"prompt": "How Memory Foam Works — viscoelastic polyurethane deforms slowly under pressure and slowly recovers. It's both viscous (resists flow like honey) and elastic (springs back like rubber). Animate the molecular chains sliding and rebounding, showing temperature dependence.", "category": "general"},
    {"prompt": "The Coastline Paradox and Fractal Dimension — measure Britain's coast with a 100km ruler: ~2800km. With a 50km ruler: ~3400km. With 1km: far more. The fractal dimension of Britain's coast is ~1.25. Animate measurement at decreasing scales with the length diverging.", "category": "mathematical_patterns"},
    {"prompt": "How WiFi Signals Propagate Through Your House — 2.4 GHz and 5 GHz radio waves reflect off metal, absorb into water and concrete, and diffract around corners. Animate a floor plan with electromagnetic wave propagation, showing dead zones and multipath interference.", "category": "real_world_applications"},
    {"prompt": "The Kessler Syndrome — space debris hits a satellite, creating more debris, hitting more satellites, in a cascade that could make low Earth orbit unusable. Animate the chain reaction and show the critical debris density threshold.", "category": "general"},
    {"prompt": "Zero-Knowledge Proofs — prove you know a secret without revealing it. The 'Ali Baba Cave' analogy: prove you know the magic word to open a door in a circular cave without the verifier seeing which direction you enter. Animate the protocol and show its application in blockchain.", "category": "real_world_applications"},
    {"prompt": "Why Do Wet Things Look Darker? — water fills surface micro-cavities, creating a smoother surface that reflects more light specularly (away from your eyes) and less diffusely (toward your eyes). Animate the light scattering on dry vs. wet rough surfaces.", "category": "counterintuitive_phenomena"},
    {"prompt": "The Two-Body Problem vs. Three-Body Problem — two gravitating bodies have a closed-form solution (Kepler orbits). Add a third body and the system becomes chaotic with no general solution. Animate stable Kepler orbits transitioning to three-body chaos.", "category": "physics_phenomena"},
    {"prompt": "Information Entropy and Optimal Coding — a fair coin has 1 bit of entropy per flip. A biased coin (90% heads) has less — you can encode sequences more efficiently. Animate Huffman coding building an optimal prefix-free code tree from character frequencies.", "category": "elegant_theorems"},
]

def send_batch(messages):
    """Send up to 10 messages in a single SQS batch."""
    entries = []
    for i, msg in enumerate(messages):
        body = {
            "prompt": msg["prompt"],
            "category": msg["category"],
            "topic_id": str(uuid.uuid4()),
            "target_duration": 90,
        }
        entries.append({
            "Id": str(i),
            "MessageBody": json.dumps(body),
        })
    resp = sqs.send_message_batch(QueueUrl=QUEUE_URL, Entries=entries)
    failed = resp.get("Failed", [])
    if failed:
        print(f"  ⚠ {len(failed)} failed: {failed}")
    return len(entries) - len(failed)

def main():
    print(f"Sending {len(TOPICS)} topics to SQS...")
    total_sent = 0
    for start in range(0, len(TOPICS), 10):
        batch = TOPICS[start : start + 10]
        sent = send_batch(batch)
        total_sent += sent
        print(f"  Batch {start // 10 + 1}: sent {sent}/{len(batch)} (total: {total_sent})")
    print(f"\nDone! {total_sent}/{len(TOPICS)} topics sent to SQS.")

if __name__ == "__main__":
    main()
